### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by busracagliyan** [pardus/pardus-pen#1]
- [x] Deficiencies in the floating widget will be completed
- [x] Icons in the toolbox will be added
- [x] An icon and setting showing the pen thickness will be added.
- [x] Save selected settings will be added
- [x] No screen recording or screenshot taking.
- [x] translation
- [x] screen - will be taken according to the largest screen size
- [x] additional feature: marker
